- exts: [js]
  run:
  - node $or_file
- exts: [go]
  run:
  - go run $or_file
- exts: [py]
  run:
  - python $or_file
- exts: [bf]
  run:
  - brainfuck $or_file
- exts: [cpp]
  run:
  - g++ -Wall $or_file 
  - ./a.out
- exts: [c]
  run:
  - gcc -Wall $or_file 
  - ./a.out
